ecommstore/ecommstore/urls.py
from django.contrib import admin
from django.urls import path, include

# for managing images (media) in FileSystemStorage
from django.conf import settings
from django.conf.urls.static import static

# admin page customisation 
#from photostore.admin import admin_site


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("photostore.urls")),
    path('users/', include("users.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommstore/photostore/urls.py
from django.urls import path

from . import views

#define namespace
app_name = "photostore"

urlpatterns = [
    path('', views.index, name='index'),
    path('search', views.search, name='search'),
    path('products', views.products, name='products'),
    path('filter_products', views.filter_products, name='filter_products'),
    path('add-to-cart/<int:product_id>', views.add_to_cart, name='add-to-cart'),
    path('change-quantity/<int:cart_id>', views.change_quantity, name='change-quantity'),
    path('remove-from-cart/<int:cart_id>', views.remove_from_cart, name='remove-from-cart'),    
    path('checkout', views.checkout, name='checkout'),
    path('payment', views.payment, name='payment'),
    path('about_us', views.about_us, name='about_us'),
    path('license', views.license, name='license'),
]

ecommstore/users/urls.py
from django.urls import path

from . import views
#from users.views import CustomLoginView

# define namespace
app_name = "users"

urlpatterns = [
    # path('login', CustomLoginView.as_view(), name='login'),
    path('login', views.login_view, name='login'),
    path('my_profile', views.user_profile, name='user_profile'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('signup', views.signup, name='signup'),
    path('logout', views.logout_view, name='logout'),
]

ecommstore/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class UserProfile(AbstractUser):
    class UserType(models.TextChoices):
        ART = 'Designer', 'Artist'
        PHOTOGRAPHY = 'Shutterbug', 'Photographer'
        CURIOSITY = 'Aficionado', 'Enthusiast'

    # AbstractUser model fields - first_name, last_name, email, username, password, is_staff, is_active, date_joined
    # define additional or custom fields
    first_name = models.CharField(max_length=100, null=False, blank=False)
    last_name = models.CharField(max_length=100, null=False, blank=False)
    email = models.EmailField(unique=True, null=False, blank=False)
    user_type = models.CharField('Profession/Hobby', max_length=20, choices=UserType.choices)
    bio = models.TextField('Bio', max_length=200, null=True, blank=True)

    def __str__(self):
        fname = f"{self.first_name}".capitalize() 
        lname = f"{self.last_name}".capitalize()
        return f"\n{fname} {lname}\n"   

ecommstore/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from users.models import UserProfile


class RegForm(UserCreationForm):
    class Meta:
        model = UserProfile
        fields = ["first_name", "last_name", "email", "user_type", "bio", "username"]
    

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = UserProfile
        fields = ["first_name", "last_name", "email", "user_type", "bio", "username"]

ecommstore/users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect

from django.contrib.auth import login, logout
# from django.contrib.auth.views import LoginView, LogoutView   # in urls.py, for django-automated templates and validation

from users.forms import RegForm, CustomUserChangeForm
from users.models import UserProfile


# Views
# REGISTRATION
def signup(request):    
    # validate request
    if request.method == "POST":
        form = RegForm(request.POST)

        if form.is_valid():          
            # save form, authenticate user
            user = form.save()
            login(request, user)

            # user session data identifier
            session_user = UserProfile.objects.get(first_name=user.first_name)
            request.session['user_id'] = session_user.id

            # session variables
            request.session['first_name'] = str(user.first_name).capitalize()
            request.session['last_name'] = str(user.last_name).capitalize()
            request.session.save()

            return HttpResponseRedirect(reverse('photostore:index'))
        
        else: # errors in registration details
            return render(request, 'users/signup.html', context={"form": form})
    else: # GET request response
        return render(request, 'users/signup.html', context={"form": RegForm()})



# LOGIN
def login_view(request):
    from django.contrib.auth.forms import AuthenticationForm

    # validate and authenticate user
    if request.method=="POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)

            # user session data identifier
            session_user = UserProfile.objects.get(first_name=user.first_name)
            # request.session['user_id'] = session_user.id
            if session_user.first_name == 'super':
                return redirect('admin:index')
            
            else:
                # session variables
                request.session['first_name'] = str(user.first_name).capitalize()
                request.session['last_name'] = str(user.last_name).capitalize()
                request.session.save()

                return HttpResponseRedirect(reverse('photostore:index'))

        else: # errors in login details
            return render(request, 'users/login.html', context={"form": form})
            
    return render(request, 'users/login.html', context={"form": AuthenticationForm()})
    


def user_profile(request):
    return render(request, 'users/user_profile.html')

def edit_profile(request):
    if request.user.is_authenticated:
        # initial_data = {'first_name': request.user.first_name,
        #                 'last_name': request.user.last_name,
        #                 'email': request.user.email,
        #                 'user_type': request.user.user_type,
        #                 'bio':request.user.bio,
        #                 'username': request.user.username
        #                 }

        # profile_data = CustomUserChangeForm(initial=initial_data)

        # if profile_data.has_changed:
        if request.method == 'POST':
            updated_profile = CustomUserChangeForm(request.POST, instance=request.user)

            if updated_profile.is_valid:
                updated_profile.save()
                return HttpResponseRedirect(reverse('users:user_profile'))
        
        profile_data = CustomUserChangeForm(instance=request.user)
        context = {'form' : profile_data, }
        return render(request, 'users/edit_profile.html', context)  
    else: # user is not authenticated
        return HttpResponseRedirect(reverse('users:login'))



# LOGOUT
def logout_view(request):
    logout(request)
    request.session.clear()

    return render(request, 'users/logout.html',context={
          "message" : "Logged out successfully!"
    })
    

ecommstore/users/templates/users/edit_profile.html
{% extends 'users/layout.html' %}
{% load static %}

{% block content %}
    <h1 class="heading">Edit My Profile</h1>
        <form action="{% url 'users:edit_profile' %}" method="POST" class="form-group">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-button register" type="submit" value="Update Profile">
            <br>
            <button class="profile-button">
                <a href="{% url 'users:user_profile' %}">Cancel</a>
            </button>
        </form>
{% endblock %}

ecommstore/users/templates/users/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Image Barter Bazaar</title>
    <link rel="stylesheet" href="{% static 'users/styles.css' %}">
    <!-- favicon --->
    <link rel="icon" href="{% static 'users/logo.png' %}">
</head>
<body>
    <div class="logo-container">
        <a href="{% url 'photostore:index' %}">
            <image class="logo" src="{% static 'users/logo.png' %}" alt="logo"/>
        </a>
    </div>
    <div class="logo-description">
        <h1 class="heading">Welcome !</h1>
        <p>
            This website is created by <a href="https://www.github.com/prak112/">Prakirth Govardhanam</a>
            <br>
            No data is stored or manipulated for any purposes. 
            <br>This is purely for learning and educational purposes.
            <br> 
            <cite>
                <p>Logo Credits : <cite><a href="https://www.freepik.com/icon/exchange_17836180#fromView=search&page=1&position=12&uuid=bbefee50-3666-4fcc-b5ed-69a999b0379f">Icon by Rahat</a>, Freepik</cite></p>
            </cite>
        </p>
    </div>

    {% block content %}
    {% endblock %}

</body>
</html>

ecommstore/users/templates/users/login.html
{% extends "users/layout.html" %}


{% block content %}

{% if message %}
    <div class="form-message">
        {{ message }}
    </div>
{% endif %}

<h1 class="heading">Login</h1>
<div class="form-container">
    <form action="{% url 'users:login' %}" method="POST" class="form-group">
        {% csrf_token %}
        {{ form.as_p }}<br>
        <div>
            <input class="form-button login" type="submit" value="Login">
        </div>
    </form>

    <p class="form-group"><b>Don't have an account ?</b></p>
    <div class="form-button register">
        <a href="{% url 'users:signup' %}" rel="noopener" target="_blank">Create Account</a>
    </div>
</div>

{% endblock %}

ecommstore/users/templates/users/logout.html
{% extends "users/layout.html" %}


{% block content %}

{% if message %}
    <div class="form-message">
        {{ message }}
    </div>
{% endif %}

<h1 class="heading">Logged Out</h1>
<div class="form-container">
<p class="form-group"> Perhaps forgot something ?</p>
    <div class="form-button login">
        <a href="{% url 'users:login' %}" class="form-button login">Back to Login</a>
    </div>
</div>

{% endblock %}

ecommstore/users/templates/users/signup.html
{% extends "users/layout.html" %}

{% block content %}

{% if message %}
    <div class="form-message">
        {{ message }}
    </div>
{% endif %}

<h1 class="heading">Sign Up</h1>
<div class="form-container">
    <form class="form-group" action="{% url 'users:signup' %}" method="POST">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
            <div class="field-wrapper">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}                    
                {% if field.help_text %}
                    <p style="font-size: 10px;">{{ field.help_text }}</p>
                {% endif %}
            </div>
        {% endfor %}
        <div>
            <input class="form-button register" type="submit" value="Sign Up">
        </div>
    </form>
    
    <p class="form-group"><b>Already have an account ?</b></p>
    <div class="form-button login">
        <a href="{% url 'users:login' %}" rel="noopener" target="_blank">Login</a>
    </div>
</div>

{% endblock %}

ecommstore/users/templates/users/user_profile.html
{% extends "users/layout.html" %}
{% load static %}

{% block content %}
    <h1 class="heading">My Profile</h1>
    <div class="profile-container">
        <ul class="profile-content">
            <li><b>Name</b> :<br>&ensp; {{ request.user.first_name }} {{ request.user.last_name }} </li>
            <li><b>Email</b> :<br>&ensp; {{ request.user.email }} </li>
            <li><b>Username</b> :<br>&ensp; {{ request.user.username }}</li>
            <li><b>Profession/Hobby</b> :<br>&ensp; {{ request.user.user_type }} </li>
            <li><b>About Me</b> :<br>&ensp; {{ request.user.bio }} </li>
        </ul>
    </div>
    <div class="profile-button">
        <a href="{% url 'users:edit_profile' %}">Edit Profile</a>
    </div>
{% endblock %}