ecommstore/ecommstore/urls.py
from django.contrib import admin
from django.urls import path, include

# for managing images (media) in FileSystemStorage
from django.conf import settings
from django.conf.urls.static import static

# admin page customisation 
#from photostore.admin import admin_site


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("photostore.urls")),
    path('users/', include("users.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommstore/photostore/urls.py
from django.urls import path

from . import views

#define namespace
app_name = "photostore"

urlpatterns = [
    path('', views.index, name='index'),
    path('search', views.search, name='search'),
    path('products', views.products, name='products'),
    path('filter_products', views.filter_products, name='filter_products'),
    path('add-to-cart/<int:product_id>', views.add_to_cart, name='add-to-cart'),
    path('change-quantity/<int:cart_id>', views.change_quantity, name='change-quantity'),
    path('remove-from-cart/<int:cart_id>', views.remove_from_cart, name='remove-from-cart'),    
    path('checkout', views.checkout, name='checkout'),
    path('payment', views.payment, name='payment'),
    path('about_us', views.about_us, name='about_us'),
    path('license', views.license, name='license'),
]

ecommstore/users/urls.py
from django.urls import path

from . import views
#from users.views import CustomLoginView

# define namespace
app_name = "users"

urlpatterns = [
    # path('login', CustomLoginView.as_view(), name='login'),
    path('login', views.login_view, name='login'),
    path('my_profile', views.user_profile, name='user_profile'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('signup', views.signup, name='signup'),
    path('logout', views.logout_view, name='logout'),
]

ecommstore/photostore/models.py
from django.db import models
from users.models import UserProfile


# Create your models here.
# Synchronized data with 'UserProfile'
class Customer(models.Model): 
    user_info = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name="user_information")
    full_name = models.CharField('Full Name', max_length=128, unique=True)
    customer_type = models.CharField('Customer Type', max_length=20)

    # build fullname in UserProfile/utils.py
    def save(self, *args, **kwargs):
        fname = f"{self.user_info.first_name}".capitalize() 
        lname = f"{self.user_info.last_name}".capitalize()
        self.full_name = f"{fname} {lname}"   
        self.customer_type = self.user_info.user_type
        super(Customer, self).save(*args, **kwargs)

    def __str__(self):
        return f"\n{self.full_name}-{self.customer_type}\n"



# Details of Images hosted on 'photostore' app
class Product(models.Model): 
    CATEGORY_CHOICES = [
        ('PH', 'Photo'),
        ('ART', 'Art'),
    ]

    THEME_CHOICES = [
        ('MT', 'Mountain'),
        ('LK', 'Lake'),
        ('PLR', 'Polar'),
        ('FRST', 'Forest'),
        ('TR','Tree'),
        ('FLWR', 'Flowers'),
    ]

    STATUS_CHOICES = [
        ('AVL', 'Available'),
        ('OOPS', 'Out of Stock')
    ]
    
    author = models.CharField('Author', max_length=100, null=True)
    title = models.CharField('Title', max_length=100, null=True)
    description = models.TextField('Image Description', max_length=200, null=True, blank=True)
    image_url = models.URLField('Source', default='https://www.pexels.com/')
    category = models.CharField('Type', max_length=10, choices=CATEGORY_CHOICES)
    theme = models.CharField('Theme', max_length=20, choices=THEME_CHOICES)
    image = models.ImageField('Image', upload_to='images', default='images/flower-gold-mohar.jpg')
    status = models.CharField('Status', max_length=30, choices=STATUS_CHOICES, default='AVL')

    def __str__(self):
        return f"\n{self.title}, authored by {self.author}\n"



# staging items for purchase
class Cart(models.Model):
    customer_info = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, related_name="potential_customers")
    item = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, related_name="products_in_cart")
    quantity = models.IntegerField(default=1, null=True)

    def save_quantity(self, *args, **kwargs):
        self.quantity = self.item.count()
        super().save_quantity(*args, **kwargs)

    def __str__(self):
        return f"\n{self.customer_info.full_name}-{self.item}\n"



# Customers' Order history
class Order(models.Model):
    ORDER_STATUS_CHOICES = [
        ('SHIP', 'Delivered by Post'),
        ('DEL', 'Delivered by Email')
    ]
    customer_order = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True, related_name="order_history")
    order_date = models.DateTimeField('Date of Order', auto_now=True)
    order_status = models.CharField('Order Status', max_length=30, choices=ORDER_STATUS_CHOICES)
    # instead of price, barter_exchange field will define checkout response
    payment = models.ForeignKey(Product, on_delete=models.CASCADE, null=True, related_name="images_exchanged")

    def __str__(self):
        return f"\n{self.customer_order.item}\n"

ecommstore/photostore/forms.py
from django import forms
from photostore.models import Product, Cart


# Search bar in nav-bar, layout.html
class SearchForm(forms.Form):
    query = forms.CharField(max_length=100, 
                            required=True,
                            widget=forms.TextInput(attrs=
                                                   {'placeholder': "Enter search like 'Mountains', 'Trees'...",
                                                    'class': "search-bar"
                                                    }))
    submit = forms.CharField(widget=forms.widgets.Input(attrs=
                                                        {'type':'submit', 'value':'Search',
                                                         'class':'search-button',
                                                        }))
    


# Details to upload image to Product Model
class PaymentForm(forms.ModelForm):
    DELIVERY_CHOICES = [('EMAIL', 'By Email'),
                        ('POST', 'By Post')]
    delivery = forms.ChoiceField(choices=DELIVERY_CHOICES, widget=forms.RadioSelect)
    class Meta:
        model = Product
        fields = ['delivery', 'image', 'author', 'title', 'description', 'image_url', 'category', 'theme']
        # customize field with help-text
        widgets = {'image': forms.ClearableFileInput(attrs=
                                                     {'help_text':'Ensure image resolution-1024 * 1024! Thanks!'
                                                      })}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['image'].label = 'Image as Payment (preferred resolution: 1024 * 1024)'

ecommstore/photostore/views.py
# import libraries
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.shortcuts import get_object_or_404


# app-related imports
from photostore.models import Customer, Product, Cart, Order #, OrderDetail
from users.models import UserProfile
from photostore.forms import SearchForm, PaymentForm
from .util import paginate, get_theme_code


# HOME views
def index(request):
    if request.user.is_authenticated:
        fname = f"{request.session.get('first_name')}".capitalize() 
        lname = f"{request.session.get('last_name')}".capitalize()
        context = {
            "message" : f"{fname} {lname}! Welcome to PG's Picsies!",
        }
        return render(request, 'photostore/index.html', context) 
    
    # if user not authenticated
    else:
        return render(request, 'photostore/index.html') 
 

def search(request):
    # django SearchForm removed, to reduce complexity
  
    # collect search terms and filter 'Product' 
    query = request.GET.get('query')
    search_results = []

    search_results = Product.objects.filter(description__icontains=query) | Product.objects.filter(title__icontains=query)

    if search_results:
        context = {
                "query" : query,
                "search_results" : search_results,
                }
        return render(request, 'photostore/search.html', context)            
    else:
        context = {
            "query" : str(query).capitalize(),
        }
        return render(request, 'photostore/not_found.html', context)



# PRODUCTS views
def products(request):
    # define pagination terms
    items_per_page = 12
    all_products = Product.objects.all()
    page_content = paginate(request, products_list=all_products, items_per_page=items_per_page)

    context = {
        "all_products": page_content,
            }
    return render(request, 'photostore/products.html', context)


def filter_products(request):
    category_selected = request.GET.get('category')
    theme_selected = request.GET.get('theme')
    author_selected = request.GET.get('author')

    selected_theme_code = get_theme_code(theme_selected)
    filtered_products = Product.objects.filter(category__icontains=category_selected) | Product.objects.filter(theme=selected_theme_code) | Product.objects.filter(author=author_selected)

    # items_per_page = 6
    # page_content = paginate(request, products_list=filtered_products, items_per_page=items_per_page)

    context = {
        "category_selected": category_selected,
        "theme_selected": theme_selected,
        "author_selected": author_selected,
        "filtered_products": filtered_products,        
    }
    return render(request, 'photostore/products.html', context)



# CHECKOUT views
# from django.http import JsonResponse

def add_to_cart(request, product_id):
    item_to_add = Product.objects.get(id=product_id)   

    # if user authenticated, insert data to Cart model
    if request.user.is_authenticated:
        #user_id = request.session.get('user_id')
        user_info = Customer.objects.get(user_info__first_name=request.user.first_name)
        cart_item = Cart()
        cart_item.customer_info = user_info
        cart_item.item = item_to_add

        # retrieve quantity
        cart_item.quantity = request.POST.get('quantity')
        if cart_item.quantity is None:
            cart_item.quantity = 1 # default value
                  
        # save cart info
        cart_item.save()

        # redirect to calling view
        calling_url = request.META.get('HTTP_REFERER')

        #TO DO - show notification
            # when user adds "In Stock" item
            # when user add "Out of Stock" item / disable 'add-to-cart' button
        return redirect(calling_url)
    else:
        return HttpResponseRedirect(reverse('users:login'))



def change_quantity(request, cart_id):
    # only authenticated user can reach this view, hence no need for .is_authenticated
    # filter Cart for cart_id
    item_to_update = Cart.objects.get(pk=cart_id)

    # update quantity of the verified cart_id
    update_quantity = request.POST.get('quantity')
    item_to_update.quantity = update_quantity
    
    # save cart
    item_to_update.save()

    # return to calling_url
    calling_url = request.META.get('HTTP_REFERER')
    return redirect(calling_url)



def remove_from_cart(request, cart_id):
    if request.user.is_authenticated:
        cart_item = Cart.objects.get(id=cart_id)
        cart_item.delete()
        
        # get referrer URL or calling_url
        calling_url = request.META.get('HTTP_REFERER')
    return redirect(calling_url)


def checkout(request):
    from datetime import datetime

    if request.user.is_authenticated:
        # If customer made payment, clear previous order cart_info
        current_time = datetime.strptime(datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f'), '%Y-%m-%d %H:%M:%S.%f')
        previous_orders = Order.objects.all()

        # customer's current items
        cart_info = Cart.objects.filter(customer_info=Customer.objects.get(user_info__first_name=request.user.first_name))     
        
        # verify customer's previous orders if any
        if previous_orders is not None:
            for paid_items in previous_orders:
                for items in cart_info:
                    # verify payment was completed for previously ordered items
                    if paid_items.order_date.replace(tzinfo=None) < current_time: 
                        # verify items paid for are not in cart_info
                        if paid_items.customer_order.item.id == items.item.id:
                            # exclude paid items from cart_info                     
                            cart_info = cart_info.exclude(id=items.item.id)  
        else:
            cart_info = []

        context = {
            'cart' : cart_info,
            }
        return render(request, 'photostore/checkout.html', context)
    else:
        return HttpResponseRedirect(reverse('users:login'))


def payment(request):
    # retrieve all 'Cart' instances (items in cart) of user logged in for context
    cart_info = Cart.objects.filter(customer_info__user_info__first_name=request.user.first_name)
    # order 'Cart' instances by id for 'Order.customer_order'
    cart_sorted = cart_info.order_by('-id').first()

    if request.method == 'POST':
        form = PaymentForm(request.POST, request.FILES)   # request.FILES to access uploaded image

        if form.is_valid():
            # save 'Product' instance from PaymentForm
            payment_info = form.save(commit=False)
            payment_info.save()

            # insert data sequentially for 'Order' model
            purchase_order = Order()            
            purchase_order.customer_order = cart_sorted

            if form.cleaned_data['delivery'] == 'EMAIL':
                purchase_order.order_status = 'DEL'
            else:
                purchase_order.order_status = 'SHIP'
            
            purchase_order.payment = payment_info
            purchase_order.save()

            context = {
                'message' : 'Thanks for shopping with us! See you soon!'    
                }
            
            return render(request, 'photostore/index.html', context)
            #return HttpResponseRedirect(reverse('photostore:index'))
        
        else:   # validate incomplete form
            context = {
                'cart' : cart_info,
                'form' : form,
                }
            return render(request, 'photostore/payment.html', context)
    
    else:   # first visit to payment
        context = {
            'cart' : cart_info,
            'form' : PaymentForm(),
            }
        return render(request, 'photostore/payment.html', context)



# OTHER views
def about_us(request):
    return render(request, 'photostore/about_us.html')

def license(request):
    return render(request, 'photostore/license.html')

ecommstore/photostore/templates/photostore/cart.html
{% extends "photostore/layout.html" %}
{% load static %}

{% block content %}
<!-- products info -->
<h1 class="heading">Checkout</h1>
    <div class="checkout-title">
        <p>
            My Cart
            <img class="checkout-cart-icon" src="{% static 'photostore/checkout-cart-icon.png' %}" alt="checkout-cart-icon"/>
            <span class="checkout-items">( {{ cart|length }} )</span>
        </p>
    </div>
    <div class="checkout-container">
    {% if request.user.is_authenticated %}   
    {% if cart %}
        {% for product in cart %}
        <div class="product-container">
            <div class="product">
                <img src="{% static product.item.image %}" alt="{{ product.item.title }}"/>
                <!--image description-->
                <p>
                    <span class="box-item-title">{{ product.item.title }}</span><br>
                    <span>{{ product.item.description }}</span><br>
                    <span>Theme : {{ product.item.get_theme_display }}</span><br>
                    
                    {% if product.category == 'PH' %}
                        <cite>Image Source : By {{ product.item.author }} from <a class="photo-source" href="{{ product.item.image_url }}">Pexels</a></cite>
                    {% else %}
                        <cite>Image Source : <a class="photo-source" href="{{ product.item.image_url }}" target="_blank" rel="noopener">Bing Image Creator</a></cite>
                    {% endif %}
                </p>           
                <div class="options">
                    <button class="change-button">
                        <form action="{% url 'photostore:add-to-cart' product_id=product.item.id %}" method="POST">
                            {% csrf_token %}
                            {% if product.quantity > 1 %}
                                <input class="quantity-input" type="number" name="quantity" id="quantity" value="{{ product.quantity }}">
                            {% else %}
                                <input class="quantity-input" type="number" name="quantity" id="quantity" value="1" min="1">
                            {% endif %}
                            <input type="submit" value="Change">   
                        </form>
                    </button>
                    <button class="remove-button">
                        <a href="">Remove</a>
                    </button>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <!-- checkout buttons -->
    <div class="goto-button-container">
        <div class="goto-button">
            <a href="{% url 'photostore:products' %}">Continue Shopping</a>
        </div>
        <div class="goto-button">
            <a href="{% url 'photostore:checkout' %}">Go To Checkout</a>
        </div>
    </div>
    <!-- if user cart is empty --->
    {% else %}
        <p class="empty-cart">Your cart is empty. <a href="{% url 'photostore:products' %}">Go Add some!</a></p>
    {% endif %}
    <!-- if user not authenticated --->        
    {% else %}
    <div class="checkout-container">
        <p class="empty-cart">Login to add products and view your cart. <a href="{% url 'users:login' %}">Login here.</a></p>
    </div>
    {% endif %}

{% endblock %}

ecommstore/photostore/templates/photostore/checkout.html
{% extends "photostore/layout.html" %}
{% load static %}

{% block content %}
<div>
<!-- user info -->
{% if request.user.is_authenticated %}
    <h1 class="heading">User Information</h1>
    <div class="user-info">
        <p>
            <span class="box-item-title">Name :</span>
            <span>{{ request.user.first_name }} {{ request.user.last_name }}</span>
        </p>
        <p>
            <span class="box-item-title">Email :</span>
            <span>{{ request.user.email }}</span>
        </p>
    </div>
{% endif %}
</div>

<div>
<!-- products info -->
    <h1 class="heading">Checkout</h1>
    <div class="checkout-title">
        <p>
            My Cart
            <img class="checkout-cart-icon" src="{% static 'photostore/checkout-cart-icon.png' %}" alt="checkout-cart-icon"/>
            <span class="checkout-items">( {{ cart|length }} )</span>
        </p>
    </div>
    <div class="spacer"></div>
    <div class="checkout-container">
    {% if request.user.is_authenticated and cart %}
        {% for product in cart %}
        <div class="product-container">
            <div class="product">
                <img src="{% static product.item.image %}" alt="{{ product.item.title }}"/>
                <!--image description-->
                <p>
                    <span class="box-item-title">{{ product.item.title }}</span><br>
                    <span>{{ product.item.description }}</span><br>
                    <span>Theme : {{ product.item.get_theme_display }}</span><br>
                    <span>Quantity: {{ product.quantity }}</span></br>

                    {% if product.category == 'PH' %}
                        <cite>Image Source : By {{ product.item.author }} from <a class="photo-source" href="{{ product.item.image_url }}">Pexels</a></cite>
                    {% else %}
                        <cite>Image Source : <a class="photo-source" href="{{ product.item.image_url }}" target="_blank" rel="noopener">Bing Image Creator</a></cite>
                    {% endif %}
                </p>           
                <div class="options">
                    <button class="add-button">
                        <form action="{% url 'photostore:change-quantity' cart_id=product.id %}" method="POST">
                            {% csrf_token %}
                            {% if product.quantity > 1 %}
                                <input class="quantity" type="number" name="quantity" id="quantity" value="{{ product.quantity }}">
                            {% else %}
                                <input class="quantity" type="number" name="quantity" id="quantity" min="1" value="1" />
                            {% endif %}
                            <input type="submit" value="Add" />   
                        </form>
                    </button>
                    <button class="remove-button">
                        <a href="{% url 'photostore:remove-from-cart' cart_id=product.id %}">REMOVE</a>
                    </button>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
    <!-- checkout buttons -->
    <div class="goto-button-container">
        <div class="goto-button">
            <a href="{% url 'photostore:products' %}">Continue Shopping</a>
        </div>
        <div class="goto-button">
            <a href="{% url 'photostore:payment' %}">Go To Payment</a>
        </div>
    </div>

    <!-- if user cart is empty --->
    {% elif not cart and request.user.is_authenticated %}
        <p class="empty-cart">Your cart is empty. <a href="{% url 'photostore:products' %}">Go Add some!</a></p>
    <!-- if user not authenticated --->        
    {% elif not request.user.is_authenticated %}
        <p class="empty-cart"> <a href="{% url 'users:login' %}">Login</a> to see your information, add products and view your cart.</p>
    {% endif %}

    <div class="spacer"></div>


</div>
{% endblock %}

ecommstore/photostore/templates/photostore/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Image Barter Bazaar</title>
    <link rel="stylesheet" href="{% static 'photostore/styles_global.css' %}">
    <link rel="stylesheet" href="{% static 'photostore/styles_index.css' %}">
    <link rel="stylesheet" href="{% static 'photostore/styles_products.css' %}">
    <link rel="stylesheet" href="{% static 'photostore/styles_checkout.css' %}">
    <link rel="stylesheet" href="{% static 'photostore/styles_about.css' %}">
    <link rel="stylesheet" href="{% static 'photostore/styles_notifications.css'  %}">
    <!--favicon-->
    <link rel="icon" href="{% static 'photostore/logo.png' %}">
</head>
<body>
    <header>
        <nav>
            <div class="logo">
                <a href="{% url 'photostore:index' %}">
                    <img class="logo" src="{% static 'photostore/logo.png' %}" alt="logo">
                </a>
            </div>
            <div class="search-area">
                <form action="{% url 'photostore:search' %}" method="GET">
                    <input class="search-bar" type="text" name="query" placeholder="Search like 'Mountains', 'Trees'..."/>
                </form>
            </div>
            {% if request.user.is_authenticated %}
                <div class="nav-menu item">
                    <a class="user-profile" href="{% url 'users:user_profile' %}">{{ request.session.first_name }}'s profile</a>
                </div>
            {% endif %}
            <div class="nav-menu item">
                {% if request.user.is_authenticated %}
                    <a class="login" href="{% url 'users:logout' %}" target="_blank" rel="noopener">Log Out</a>
                {% else %}
                    <a class="login" href="{% url 'users:login' %}" target="_blank" rel="noopener">Log In</a>
                {% endif %}
            </div>
            <div class="nav-menu item">
                <a href="{% url 'photostore:products' %}" target="_blank" rel="noopener">Products</a>
            </div>
            <div class="nav-menu item">
                <a href="{% url 'photostore:about_us' %}" target="_blank" rel="noopener">About Us</a>
            </div>
            <div class="nav-menu item">
                <a class="checkout-cart-icon" href="{% url 'photostore:checkout' %}" target="_blank" rel="noopener">
                    <img class="checkout-cart-icon" src="{% static 'photostore/checkout-cart-icon.png' %}" alt="checkout-cart-icon">
                </a>
            </div>
        </nav>
    </header>    
    {% if request.session.product_added %}
        {% include 'photostore/notifications.html' %}
    {% endif %}

    {% block content %}
    {% endblock %}


    <footer>
        <nav>
            <div class="logo-container">
                <a href="{% url 'photostore:index' %}">
                    <img class="logo" src="{% static 'photostore/logo.png' %}" alt="logo">
                    <div class="logo-text">
                        <p>Image Barter Bazaar © 2024</p>
                        <p>Learning & Educational purposes only.</p>
                    </div>
                </a>
            </div>
            <ul>
                <li>
                    <a href="{% url 'photostore:about_us' %}" target="_blank" rel="noopener">About Us</a>
                    <p>Located on Planet Earth</p>
                    <p>Barter & Trade commerce</p>
                </li>
                <li>
                    <a href="{% url 'photostore:products' %}" target="_blank" rel="noopener">Products</a>
                    <p>Logo Credits : <cite><a href="https://www.freepik.com/icon/exchange_17836180#fromView=search&page=1&position=12&uuid=bbefee50-3666-4fcc-b5ed-69a999b0379f">Icon by Rahat</a>, Freepik</cite></p>  
                    <p>Photo Credits : <cite>Pexels</cite></p>
                    <p>Art Credits : <cite>Bing Image Creator</cite> & <cite>Pexels</cite></p>
                    <p>Cart Icons Credits :  <cite><a href="https://www.pikpng.com/search.html?k=cart+icon">Pikpng</a></cite></p>
                </li>
                <li>
                    <a href="{% url 'photostore:license' %}" target="_blank" rel="noopener">Copyrights</a>
                    <p>MIT License : Free to Use</p>
                    <p>Remember to cite source!</p>
                    <p>Copyright © 2024</p>
                </li>
            </ul>
        </nav>
    </footer>

</body>
</html>

ecommstore/photostore/templates/photostore/not_found.html
{% extends "photostore/layout.html" %}
{% load static %}


{% block content %}
    <h2 class="heading">Oops! No images for "{{ query }}" yet.</h2>
    <div>
        <p>
            <span class="box-item-title">Contribute if you can</span>
            <p>Add images to this theme :</p>
            <button>
                <a href="">Upload Here</a>
            </button>
        </p>
    </div>
{% endblock %}

ecommstore/photostore/templates/photostore/notifications.html
{% load static %}

{% if request.session.product_added %}

    <div class="notification">
        <p>Added to Cart!</p>
        <!-- <button><b>Close</b></button> -->
    </div>

{% endif %}

ecommstore/photostore/templates/photostore/payment.html
{% extends "photostore/layout.html" %}
{% load static %}


{% block content %}
<!-- user info, products info, payment info -->

    <div class="payment-title">
        <p>
            Payment
            <img class="checkout-cart-icon" src="{% static 'photostore/checkout-cart-icon.png' %}" alt="checkout-cart-icon"/>
            <span class="payment-items">( {{ cart|length }} )</span>
        </p>
    </div>

    <!---user info-->
    <h1 class="heading">User Information</h1>
    <div class="user-info">
        <p>
            <span class="box-item-title">Name :</span>
            <span>{{ request.session.first_name }} {{ request.session.last_name }}</span>
        </p>
        <p>
            <span class="box-item-title">Email :</span>
            <span>{{ request.user.email }}</span>
        </p>
    </div>

    <div class="spacer"></div>

    <!-- payment info -->
    <div class="payment-container">
        <div class="payment-title">
            <p>
                Payment
                <img class="checkout-cart-icon" src="{% static 'photostore/checkout-cart-icon.png' %}" alt="checkout-cart-icon"/>
                <span class="payment-items">( {{ cart|length }} )</span>
            </p>
        </div>
        <div class="payment-procedure">
            <p>
                Payment procedure is simple.<br><br>Upload an image (photo or art)&nbsp;&nbsp;relevant to Nature either
                digital or manual. However, you should be the only one holding the copyrights, i.e., image should be your
                own creation.<br><br>If you feel generous, feel free to upload more 🫶🏻        
            </p>
        </div>

        <div class="spacer"></div>
        
        <div class="items-purchased">
            <p class="heading">Items in the Cart</p>
            <table>
                <th>Product</th>
                <th>Category</th>
                <th>Theme</th>
                <th>Quantity</th>
                {% for product in cart %}
                <tr>
                    <td>{{ product.item.title }}</td>
                    <td>{{ product.item.get_category_display }}</td>
                    <td>{{ product.item.get_theme_display }}</td>
                    <td>{{ product.quantity }}</td>
                    <td>
                        <button class="remove-button">
                            <a href="{% url 'photostore:remove-from-cart' cart_id=product.id %}">Remove</a>
                        </button>
                    </td>
                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="spacer"></div>
        <div class="goto-button">
            <a href="{% url 'photostore:checkout' %}">Return To Checkout</a>
        </div>
    </div>    
    
    <h1 class="heading">Payment Details</h1>
    <div class="checkout-title">
        <p>
            My Cart
            <img class="checkout-cart-icon" src="{% static 'photostore/checkout-cart-icon.png' %}" alt="checkout-cart-icon"/>
            <span class="checkout-items">( {{ cart|length }} )</span>
        </p>
    </div>   

    <div class="payment-form">
        <form action="{% url 'photostore:payment' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
            <p>
                {{ field.errors }}
                {{ field.label_tag }}<br>
                {{ field }}<br>
            </p>
            {% endfor %}
            <br>
            <button>
                <input class="button" type="submit" value="Upload Image">
            </button>
        </form>        
        <h2 class="heading">Thank you for your support! 🫶🏻</h2>
    </div>

{% endblock %}